### ISSUE TITLE
Styling by value does not work with boolean fields

### ISSUE THREAD

**Issue by ramiroaznar** [CartoDB/cartodb#10000]
Styling by value does not work with boolean fields (Turbo-Carto\* is not applied).
### STR
- Create a map with a dataset with a boolean field.
- Click on `STYLE`.
- Click on color `FILL`.
- Select `BY VALUE` and choose the boolean field. The expected result would be a categoric map, instead what is showing is a simple map (screenshot). 

![boolean](https://cloud.githubusercontent.com/assets/5215798/19070322/f1ccb242-8a2a-11e6-986c-86d0223bb5bd.png)

*CartoCSS:

``` css
#layer {
  marker-width: 7;
  marker-fill: ramp([arrest], (#5B3F95, #1D6996), ("false", "true"));
  marker-fill-opacity: 1;
  marker-allow-overlap: true;
  marker-line-width: 1;
  marker-line-color: #FFF;
  marker-line-opacity: 1;
}
```
