### ISSUE TITLE
Disable some analysis because of missing dataservices

### ISSUE THREAD

**Issue by luisbosque** [CartoDB/cartodb#10771]
Some analysis depend on external dataservices like data observatory, geocoding, isolines, etc..
If the instance is not configured to have these services, analysis depending on them should not be available.

At this moment, there are two places in app_config.yml where we are setting the url of dataservices:

```yaml
geocoder:
  api:
    host:
    port:
    user:
    dname
```

and

```yaml
aggregation_tables:
  host:
  port:
  dbname:
  username:
  password:
```

Not totally sure if there is any other attribute with info about dataservices.

I think the best thing to do would be disable these analysis when the attributes are empty or not exist.

Any other suggestion?
