### ISSUE TITLE
Analysis queue is not showing states correctly 

### ISSUE THREAD

**Issue by noguerol** [CartoDB/cartodb#10944]
Analysis verbose in Builder is not correctly showing states, as is reading "enqueued" when its actually running as per the api. 

You can download the .carto here https://drive.google.com/open?id=0B0nG__Cq6i-7elRjenRZazZoZW8

This happens when solving node D3

**Comment by xavijam** [comment]
We have these messages, not sure if they are ok:

```yml
…
"pending": "Analysis %{nodeId} running...",
"waiting": "Analysis %{nodeId} enqueued...",
"completed": "Analysis %{nodeId} completed",
"failed": "Analysis %{nodeId} failed",
"removed": "Analysis %{nodeId} deleted",
…
```
