### ISSUE TITLE
Alphamarker image necessary for heatmap (Pixel) style should be included in assets pipeline

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#10950]
Basically we are generating the current CartoCSS for this type of style:

```css
Map {
  -torque-frame-count: 1;
  -torque-animation-duration: 30;
  -torque-time-attribute: "cartodb_id";
  -torque-aggregation-function: "count(1)";
  -torque-resolution: 4;
  -torque-data-aggregation: linear;
}
#layer {
  marker-width: 45;
  marker-fill: white;
  marker-fill-opacity: 1;
  marker-file: url(http://s3.amazonaws.com/com.cartodb.assets.static/alphamarker.png);
  marker-allow-overlap: true;
  marker-line-width: 1;
  marker-line-color: #FFF;
  marker-line-opacity: 1;
  image-filters: colorize-alpha(#4b2991,#872ca2,#c0369d,#ea4f88,#fa7876,#f6a97a,#edd9a3);
}
```

In on premises will not work because the don't have access to external resources
