### ISSUE TITLE
Previous style is applied after reopening a map and applying a new style

### ISSUE THREAD

**Issue by ramiroaznar** [CartoDB/cartodb#11308]
### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. Create a map selecting `ne_10m_railroads` dataset
2. Style color layer based upon `cartodb_id` field from the UI
3. Back to the main menu
4. Open the map again
5. Change style using the CartoCSS panel:

```css
#layer {
  line-width: 1.5;
  line-color: ramp([cartodb_id], (#00e6a4,#a7e369, #e6de00,#ed8d36,#e60042), jenks);
  line-opacity: 0.9;
}
```

6. Apply (clicking or typing `CTRL+S`)

### Current Result

* A previous CartoCSS appears in the panel and the style associated with it is applied.

```css
#layer {
  line-width: 1.5;
  line-color: ramp([cartodb_id], (#00e6a4,#a7e369, #e6de00,#ed8d36,#e60042), jenks);
}
```

![cartocss](https://cloud.githubusercontent.com/assets/5215798/22115255/90e3c092-de6c-11e6-9414-f3d2899221ee.png)

* Surprisingly, moving with the arrow you can go back and then forward to the "last" CartoCSS and apply again.

### Expected result

* CartoCSS and style should be applied correctly.

### Browser and version

* Google Chrome v54.

### .carto file

* [Untitled Map (on 2017-01-19 at 16.24.09).carto.zip](https://github.com/CartoDB/cartodb/files/717173/Untitled.Map.on.2017-01-19.at.16.24.09.carto.zip)
