### ISSUE TITLE
line-offset makes the tile borders visible

### ISSUE THREAD

**Issue by AbelVM** [CartoDB/cartodb#12017]
### Context
Trying to style a layer using `line-offset` and the tiles borders become visible as a side effect

### Steps to Reproduce
1. Create a map from a polygon dataset or from scratch with an empty layer, and then draw a polygon by hand
2. Style the layer with an extra border with Npx offset as
```css
#layer {
  polygon-fill: #374c70;
  polygon-opacity: 0;
  line-width: 2;
  line-color:red;
  line-opacity: 1;
}
#layer::2 {
  polygon-fill: #374c70;
  polygon-opacity: 0;
  line-width: 2;
  line-color: blue;
  line-opacity: 1;
  line-offset:-3;
}
```

### Current Result
**red lines:** actual polygon border
**blue lines:** polygon border with offset

* If offset is < 0: the tiles that intersect my polygon has visible borders **inside** the polygon
![image](https://cloud.githubusercontent.com/assets/9017165/25138222/40269cd6-245a-11e7-815b-9107b2196f7d.png)

* If offset = 0: Behavior as expected
![image](https://cloud.githubusercontent.com/assets/9017165/25138245/4e1ba43a-245a-11e7-9cd0-8bc6c8341e5a.png)

* if offset > 0: the tiles that intersect my polygon has visible borders **outside** the polygon
![image](https://cloud.githubusercontent.com/assets/9017165/25138277/657a0b08-245a-11e7-8ad3-237c05657375.png)

### Expected result
Just no tiles borders :)

### Browser and version
Any

### .carto file
[test_offset.carto.zip](https://github.com/CartoDB/cartodb/files/930176/test_offset.carto.zip)

### Additional info
*Please add any information of interest here below*

**Comment by makella** [comment]
Sorry I never posted, but found a temporary workaround haven't tested lately, but you can see here

![tile-artifacts](https://user-images.githubusercontent.com/1566273/36804683-8bcd0fa0-1c78-11e8-97e9-2aba39f2f7ed.gif)

**Comment by rafatower** [comment]
It can be reproduced easily in local, with and without metatiling. I could not confirm it yet, but I'm pretty sure the bug is within mapnik, most likely around these lines:

https://github.com/mapnik/mapnik/pull/2955/files

(offset converter, line symbolizer)

Aside, as @makella pointed out, there's a workaround to it, that I reproduce:
```css
#layer {
  
  // Use just one layer w/ 2 styles
  // this line-width below prevents the grid effect
  line-width: 0;
  
  ::top {
  	polygon-fill: #374c70;
  	polygon-opacity: 0;
  	line-width: 2;
  	line-color:red;
  	line-opacity: 1;
  }
  ::2 {
    polygon-fill: #374c70;
  	polygon-opacity: 0;
  	line-width: 2;
    line-color: blue;
    line-opacity: 1;
    line-offset: -3;
  }
}
```

I created a PR reverting the suspect change: https://github.com/CartoDB/mapnik/pull/59

but did not have time to test it. Mind that this is just a hail mary pass in an attempt of quickly fixing it...
