### ISSUE TITLE
Help to configure HERE maps on CartoDB Builder (config/app_config.yml)

### ISSUE THREAD

**Issue by guiuprado** [CartoDB/cartodb#12430]
Hello, please I need a help.
I'm installing the CartoDB platform on productive environment. I'm working on about 2 weeks with all tutorials I can find with Google, reading the repository documentation, and all stuff that can help me to finish this job.
I'm stuck to configurate HERE basemaps, I have the app_id and app_code. I'm try to configurate by file config/app_config.yml, but without successful.
I try basically everything I could find on the web but still can't show the option on CartoDB Builder.
So please any one can help or point me where I can find some documentation?
Thanks alot for build this amazing platform and make free for community.
Thanks again.

**Comment by xavijam** [comment]
Hi @guiuprado, sorry but we don't provide this kind of help here, for that purpose we have 
But in any case, let me help you here. What have you added in your config? I guess something like this could work:

```yml
…
Here:
  nokia_day:
    url: 'https://{s}.base.maps.api.here.com/maptile/2.1/maptile/newest/normal.day/{z}/{x}/{y}/256/png8?lg=eng&token={{ your_token }}&app_id={{ your_app_id }}'
    subdomains: '1234'
    minZoom: '0'
    maxZoom: '20'
    name: 'HERE day'
    className: 'nokia_day'
    attribution: ''&copy;'+year.to_s+' HERE <a href="http://here.net/services/terms" target="_blank">Terms of use</a>'
…
```
This piece of code should be under `basemaps`.
