### ISSUE TITLE
Wrong CORS for local images

### ISSUE THREAD

**Issue by Jesus89** [CartoDB/cartodb#12647]
### Context

In the development environment, I try to upload an image to be used in the legends. I can upload correctly the image, but when I GET, it throws the following error:

```
Access to Image at
'http://localhost.lan:3000/uploads/development/cdb/assets/20170824104218Selection_010.png?req=markup'
from origin 'http://cdb.localhost.lan:3000'
has been blocked by CORS policy: No 'Access-Control-Allow-Origin'
header is present on the requested resource.
Origin 'http://cdb.localhost.lan:3000' is therefore not allowed access.
```

### Steps to Reproduce

1. Create a Category legend (Style > Fill)
2. Upload a local image to the server
3. Select the uploaded image

### Current Result

It would be nice to get the correct headers for the image.

Also default access keys should be changed to "":

```
aws:
    s3:
      access_key_id: "test"
      secret_access_key: "test"
  assets:
    s3_bucket_name: "test"
```

```
aws:
    s3:
      access_key_id: ""
      secret_access_key: ""
  assets:
    s3_bucket_name: ""
```

+@javitonino
