### ISSUE TITLE
Disable editing the "Others" icon in UI (only in advanced mode)

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#12683]
## Steps to reproduce
- Create a map with a layers of points.
- Style the layer by value, using a string column.
- Try to select a column with more than 10 different strings.
- Add an icon to the first result, legend and map should reflect that change.
- Now, set another icon to "Others" value.
- Map has changed and that icon is being applied to all categories except the first one.

cc @Jesus89

**Comment by xavijam** [comment]
I feel it is a problem about how we generate the CartoCSS. For example, with the steps above, the generated CartoCSS is:

```css
#layer {
  marker-width: 20;
  marker-fill: ramp([nameascii], (#5F4690, #1D6996, #38A6A5, #0F8554, #73AF48, #EDAD08, #E17C05, #CC503E, #94346E, #6F4070, #666666), ("Springfield", "Victoria", "Albany", "Alexandria", "Douglas", "Greenville", "Hamilton", "La Paz", "Mercedes", "Richmond"), "=");
  marker-fill-opacity: 1;
  marker-file: ramp([nameascii], (url('https://s3.amazonaws.com/com.cartodb.users-assets.production/maki-icons/triangle-stroked-18.svg'), url('https://s3.amazonaws.com/com.cartodb.users-assets.production/maki-icons/museum-18.svg'), url('https://s3.amazonaws.com/com.cartodb.users-assets.production/maki-icons/cemetery-18.svg')), ("Springfield", "Victoria"), "=");
  marker-allow-overlap: true;
  marker-line-width: 1;
  marker-line-color: #FFF;
  marker-line-opacity: 1;
}
```

I feel we should generate all the options in the maker-file attribute, adding nulls when icons are not set.

```css
#layer {
  marker-width: 20;
  marker-fill: ramp([nameascii], (#5F4690, #1D6996, #38A6A5, #0F8554, #73AF48, #EDAD08, #E17C05, #CC503E, #94346E, #6F4070, #666666), ("Springfield", "Victoria", "Albany", "Alexandria", "Douglas", "Greenville", "Hamilton", "La Paz", "Mercedes", "Richmond"), "=");
  marker-fill-opacity: 1;
  marker-file: ramp([nameascii], (url('https://s3.amazonaws.com/com.cartodb.users-assets.production/maki-icons/triangle-stroked-18.svg'),url(),url(),url(),url(),url(),url(),url(),url(), url('https://s3.amazonaws.com/com.cartodb.users-assets.production/maki-icons/museum-18.svg'), url('https://s3.amazonaws.com/com.cartodb.users-assets.production/maki-icons/cemetery-18.svg')), ("Springfield", "Victoria", "Albany", "Alexandria", "Douglas", "Greenville", "Hamilton", "La Paz", "Mercedes", "Richmond"), "=");
  marker-allow-overlap: true;
  marker-line-width: 1;
  marker-line-color: #FFF;
  marker-line-opacity: 1;
}
```
