### ISSUE TITLE
Inconsistent aggregation methods

### ISSUE THREAD

**Issue by ramiroaznar** [CartoDB/cartodb#12927]
### Context

* Most of the aggregation methods returns very disturbing maps.

### Steps to Reproduce

1. Create a new map selecting `populated_places` dataset from CARTO's Data Library
2. Click on the layer and go to the `STYLE` tab
3. Select `Admin. Regions` method from the Aggregation carousel.
4. Toggle between the different quantification methods.

#### Quantiles

![quantiles](https://user-images.githubusercontent.com/5215798/31336162-f33c3078-acf5-11e7-8208-c1dcceeb4692.png)

#### Jenks

![jenks](https://user-images.githubusercontent.com/5215798/31336189-0a3f1c86-acf6-11e7-84e8-ace43c1f5129.png)

#### Equal Intervals

![equal](https://user-images.githubusercontent.com/5215798/31336215-26b56988-acf6-11e7-9c7b-7100da03502b.png)

#### Head/tails

![head-tails](https://user-images.githubusercontent.com/5215798/31336247-44f33b82-acf6-11e7-88b7-dd3a0acd4799.png)

### Expected result

* Our jenks data classification method is far different from R and other software applications.

#### CARTO statistical functions

```sql
SELECT CDB_JenksBins(array_agg(num_field), 6) FROM table_name where num_field is not null
```

```
"cdb_jenksbins": [1,1,1,1,89,47969]
```

#### TurboCARTO

```css
#layer {
  marker-width: ramp([num_field], range(3,45), jenks(7));
}
```

#### CartoCSS

```css
#layer {
  marker-width: 3;
  [ num_field > 1 ] {
    marker-width: 10
  }
  [ num_field > 1 ] {
    marker-width: 17
  }
  [ num_field > 1 ] {
    marker-width: 24
  }
  [ num_field > 1 ] {
    marker-width: 31
  }
  [ num_field > 1 ] {
    marker-width: 38
  }
  [ num_field > 89 ] {
    marker-width: 45
  }
}
```

#### R

```r
data <- read.csv(file="table_name.csv", head=TRUE,sep=",")
View(data)
values <- data [['num_field']]
head(values)
classIntervals(values, 7, style="jenks")
```

```
[0,69]     (69,354]   (354,1008]  (1008,2174]  (2174,3346]  (3346,5605] (5605,47969] 
 17421          443           76           35            6            5            1 
 ```

### Browser and version

* Google Chrome Versión 61.0.3163.100 (Build oficial) (64 bits)

### .carto file

* [Agg. Methods (on 2017-10-09 at 15.46.18).carto.zip](https://github.com/CartoDB/cartodb/files/1369091/Agg.Methods.on.2017-10-09.at.15.46.18.carto.zip)
