### ISSUE TITLE
Ability to customize emails for the organization

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#14627]
We want to have an option for our outgoing emails to be customizable in the same way the login screen is, that is, use the organization logo and name instead of the CARTO brand.

Basically:
- Header & footer: CARTO logo -> Organization logo
- Subject: CARTO -> Organization name
- Body: CARTO -> Organization name

This should be an option that is set globally by some setting in `app_config` as we don't want to enable email customization in all installations, only some of them.

Some example changes for the password reset email, we need to change three files, the mailer for the subject, the mail template itself for some texts and the email header for the logo.
```
  def password_reset(user)
    @user = user
    @organization = @user.organization
    @subject = "Reset XXXXXXXXXXX password"
    base_url = CartoDB.base_url(@organization.try(:name))
    path = CartoDB.path(self, 'edit_password_reset', id: @user.password_reset_token)
    @password_reset_link = "#{base_url}#{path}"
    mail to: @user.email, subject: @subject
  end
```

```
<tr>
  <td align="left" style="font-size: 14px; line-height: 25px; font-family: 'Open Sans', Helvetica, Arial, sans-serif; color: #647083;">
    <p>If you didn’t request to change your password please ignore this email.</p>
    <p><%= link_to 'Click here', @password_reset_link, :style=>"color: #1181FB;" %> to reset your password and define a new one.</p>
    <p>The XXXXXXXXXXXXXX team.</p>
  </td>
</tr>
```

```
<table border="0" cellpadding="0" cellspacing="0" width="100%">
  <tr>
    <td bgcolor="#ffffff">
      <div align="center" style="padding: 0px 15px 0px 15px; <%= invitation.present? ? "background-image: url('http://carto-email-assets.s3.amazonaws.com/confetti.png'); background-position: center top; background-repeat: no-repeat;" : "" %>">
        <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 620px; width: 100% !important;">
          <tr>
            <td style="padding: 20px 0px 65px 0px;" class="logo">
              <table border="0" cellpadding="0" cellspacing="0" width="100%">
                <tr>
                  <td bgcolor="#ffffff" width="40" align="left"><img alt="Logo" src="http://carto-email-assets.s3.amazonaws.com/XXXXXXXX-logo.png" width="82" height="32" style="display: block;" border="0"></td>
                  <td bgcolor="#ffffff" width="560" align="right">
                  </td>
                </tr>
              </table>
            </td>
          </tr>
        </table>
      </div>
    </td>
  </tr>
</table>

```

It doesn't have to be perfect at first try, we'll probably forget about some email, but let's try to get as much of them as possible.

cc @jorgesancha @xavipereztr @ernesmb This is what we discussed.

**Comment by alrocar** [comment]
@javitonino thanks for the issue description :)

If I understood it correctly this is about removing any reference to the `CARTO` brand in favour of the organization name and logo in e-mails, right?

A couple of questions:

- I see you mention adding some config in `app_config.ynml` Is it because this is only for onpremises? 
- Would it make sense otherwise, using the `no_map_logo` attribute present in the organizations table 
for this purpose?

**Comment by javitonino** [comment]
> If I understood it correctly this is about removing any reference to the CARTO brand in favour of the organization name and logo in e-mails, right?

Yes

A couple of questions:

> I see you mention adding some config in app_config.ynml Is it because this is only for onpremises?

Yes. Only some of them.

> Would it make sense otherwise, using the no_map_logo attribute present in the organizations table for this purpose?

Uhm, maybe. But this is a different feature that we may want to keep independent. Although they are similar in spirit (remove CARTO branding), the usecase for each one is not exactly the same.

**Comment by alrocar** [comment]
For further reference, I'm using [this emails list](https://docs.google.com/spreadsheets/d/1j5Ke5UtUjKv5TmY1pwKIDnnhhIYwqoFd-E0esIYUQC8/edit#gid=0) (made recently)

**Comment by alrocar** [comment]
Some stuff is now configurable from the `app_config.yml` by including a section like the one, under the `mailer` section:

```yml
  template:
      # The name of the app
      app_name: 'CARTO'
      # A link to the app or documentation about it
      app_link: 'https://carto.com'
      # A public URL for the header image in the emails (it's resized to 82 pixels wide)
      header_logo_url: 'http://carto-email-assets.s3.amazonaws.com/carto-logo.png'
      # A text for the footer
      footer_text: 'CARTO · Made in Madrid & New York City since 2012'
      # A link to get support (it may be a mailto, or just a URL)
      support_link: 'mailto:support@carto.com'
      # False to avoid including references to our documentation
      include_carto_links: false
```
