### ISSUE TITLE
Trouble getting active_support to connect to db

### ISSUE THREAD

**Issue by knownasilya** [CartoDB/cartodb#16069]
### Context
Trying to start carto, and get this error:

```sh
editor_1    | /usr/local/bundle/gems/activesupport-4.2.11.3/lib/active_support/dependencies.rb:274:in `require': Could not load 'active_record/connection_adapters/postgres_adapter'. Make sure that the adapter in config/database.yml is valid. If you use an adapter other than 'mysql', 'mysql2', 'postgresql' or 'sqlite3' add the necessary adapter gem to the Gemfile. (LoadError)
```

My database config input looks like so:

```yaml
development:
  adapter: postgres
  encoding: unicode
  host: postgres # name of service in docker compose setup
  port: 5432
  database: carto_db_production
  username: postgres
  password: test
  conn_validator_timeout: 900
```

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. Follow guide to start carto (latest tag or master)
2. `RAILS_ENV=development bundle exec rails s -p 3000`
3. See error

### Current Result
```sh
editor_1    | /usr/local/bundle/gems/activesupport-4.2.11.3/lib/active_support/dependencies.rb:274:in `require': Could not load 'active_record/connection_adapters/postgres_adapter'. Make sure that the adapter in config/database.yml is valid. If you use an adapter other than 'mysql', 'mysql2', 'postgresql' or 'sqlite3' add the necessary adapter gem to the Gemfile. (LoadError)
```

### Expected result
Expect the editor to start. 

### Browser and version
*What internet browser (Chrome, Firefox, etc) and version was you using and version*
Chrome, but doesn't apply. Running carto in docker using Ubuntu 16.
Tried this in latest tagged release and master branch, same results.

### Additional info
*Please add any information of interest here below*
