### ISSUE TITLE
Torque layers should send all cartocss

### ISSUE THREAD

**Issue by rochoa** [CartoDB/cartodb#2252]
Torque layers created in the editor are only sending the `Map` object in mapconfig's cartocss that restricts what the Maps API can do with it server side.

As an example, for a torque layer with cartocss as:

```css
/** torque visualization */

Map {
-torque-frame-count:512;
-torque-animation-duration:30;
-torque-time-attribute:"cartodb_id";
-torque-aggregation-function:"count(cartodb_id)";
-torque-resolution:2;
-torque-data-aggregation:linear;
}

#ne_10m_populated_places_simple_1_1{
  comp-op: lighter;
  marker-fill-opacity: 0.9;
  marker-line-color: #FFF;
  marker-line-width: 1.5;
  marker-line-opacity: 1;
  marker-type: ellipse;
  marker-width: 6;
  marker-fill: #FF9900;
}
#ne_10m_populated_places_simple_1_1[frame-offset=1] {
 marker-width:8;
 marker-fill-opacity:0.45; 
}
#ne_10m_populated_places_simple_1_1[frame-offset=2] {
 marker-width:10;
 marker-fill-opacity:0.225; 
}
```

It's sending only the following in the mapconfig:
```json
{
    "layers": [
        {
            "options": {
                "cartocss": "Map{-torque-frame-count:512;-torque-resolution:2;-torque-aggregation-function:'count(cartodb_id)';-torque-time-attribute:'cartodb_id';-torque-data-aggregation:linear;}",
                "cartocss_version": "1.0.0",
                "sql": "select * from ne_10m_populated_places_simple_1_1"
            },
            "type": "torque"
        }
    ],
    "version": "1.0.1"
}
```

However I would like/expect to get the whole cartocss for the layer.
