### ISSUE TITLE
static map image only showing first step of torque animation

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/cartodb#3268]
When generating static map images in the editor, the first step is rendered, not the one that's currently selected in the editor. This screen cap is a side-by-side comparison between a view in the editor vs. an image produced from the static maps api. No matter which step the animation is on (while paused or not), the shows a capture of only the first step. The CartoCSS used is below the image. Same effect happens whether on `cumulative` or `linear`.

![screen shot 2015-04-19 at 20 16 52](https://cloud.githubusercontent.com/assets/1041056/7222037/c3b07374-e6d1-11e4-8d92-dca5ca6541a1.png)

``` css
/** torque visualization */

Map {
-torque-frame-count:512;
-torque-animation-duration:30;
-torque-time-attribute:"date_field";
-torque-aggregation-function:"count(cartodb_id)";
-torque-resolution:2;
-torque-data-aggregation:cumulative;
}

#tracks{
  comp-op: lighter;
  marker-fill-opacity: 0.9;
  marker-line-color: #FFF;
  marker-line-width: 0;
  marker-line-opacity: 1;
  marker-type: ellipse;
  marker-width: 3.5;
  marker-fill: #FF9900;
}
#tracks[frame-offset=1] {
 marker-width:5.5;
 marker-fill-opacity:0.45; 
}
#tracks[frame-offset=2] {
 marker-width:7.5;
 marker-fill-opacity:0.225; 
}
```

maybe cdb headquarters is too hipster rainbow ;)
