### ISSUE TITLE
several problems using subdomainless urls

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#3334]
the setup is the following:

```
  session_domain:     'localhost.lan:3000'
  subdomainless_urls: true
```

the machine url is http://192.168.1.188:3000

- [x] when I got to http://192.168.1.188:3000/login, "192.168.1.188" appears as the user in the form. It should be empty
- [x] when I login using user "cartodb" I get redirected to http://192.168.1.188.localhost.lan:3000/user/cartodb/dashboard/ (it should be http://192.168.1.188:3000/user/cartodb/dashboard/
- [x] when I write http://192.168.1.188:3000/user/cartodb/dashboard/ this is user_data.base_url

```
"http://192.168.1.188.localhost:3000/user/cartodb"
```

We should provide access using a single IP addreess

**Comment by santisaez** [comment]
@Kartones I have done some tests enabling subdomain-less URLs feature and accessing to the dashboard/editor using the domain name, instead of the IP, and seems there are some new issues.

Relevant `app_config` settings:

```ruby
session_domain: 'subdomain.example.com'
subdomainless_urls: true
account_host: '${organization}.subdomain.example.com' # see [1]
```

[1] see https://github.com/CartoDB/cartodb-onpremise/issues/226 since this could be a misconfigured setting, just for the record.

When I go to `https://${organization}.subdomain.example.com/login` I get an incorrect username **with with a dot** as suffix, something like the issue reported by @javisantana:

![login_bad](https://cloud.githubusercontent.com/assets/223956/7316891/47a79e3a-ea7b-11e4-8001-05124aac3753.png)

Also, when clicking on the "logout" link I'm redirect to the following URL `https://maps.subdomain.example.com/user/maps./maps` - in this case, "maps" is the organization name and "maps-admin" the organization admin' username.

**Comment by rafatower** [comment]
> when I write http://192.168.1.188:3000/user/cartodb/dashboard/ this is user_data.base_url

@javisantana I don't get what you mean here in the description of the ticket.

**Comment by javisantana** [comment]
ok, sorry, what I meant is:

- having an user called 'cartodb' and the config.yml as I pasted
- when I write this url http://192.168.1.188:3000/user/cartodb/dashboard/ the base_url sent to client side is wrong

You can check out base_url going to a dataset, open developer tools and print user_data.base_url. 

FYI base_url is the url we use to access API endpoints from client side

**Comment by rafatower** [comment]
Just a quick note about the config in the ticket description: the port shouldn't be part of the `session_domain`, there are other entries `http_port` and `https_port` that should be used instead.

**Comment by rafatower** [comment]
The relevant parts of the config:
```yaml
#File config/app_config.yml

  http_port: 3000      # nil|integer. HTTP port to use when building urls. Leave empty to use default (80)
  https_port: null # nil|integer. HTTPS port to use when building urls. Leave empty to use default (443)

  session_domain:     '172.17.0.1'    # note there's NO port here
  subdomainless_urls: true

  account_host:       '172.17.0.1:3000' # note there's port here
```
