### ISSUE TITLE
Items in public map and dataset has a weird separator

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#5072]
![screen shot 2015-08-18 at 10 20 27](https://cloud.githubusercontent.com/assets/132146/9325461/ce4389c8-4592-11e5-8efc-c18a1b1c610c.png)

And please if it is possible, don't use this kind of separator:

``` css
.Navmenu-sep {
  position: absolute;
  left: 0;
  display: inline-block;
  margin-left: -20px;
  margin-right: 20px;
  width: 1px;
  height: 20px;
  background-color: $cNavmenu-sep;
}
```

I encourage you to try to use the separator with other properties instead of negative margins.
