### ISSUE TITLE
Using column names with double quotes returns &quot; in CartoCSS text-name param

### ISSUE THREAD

**Issue by ztephm** [CartoDB/cartodb#5181]
Ref S/B 6359040 - ping @saleiva not sure who this gets assigned to?

User wants to concatenate column values with double quotes in a label. 

Using:
text-name: [column_1] + ' \"   ' + [column_2]; 

Expected is: 
column_1_val" column_2_val

What shows:
column_1_val&quot; column_2

Using two single quotes in the meantime as a work-around.

**Comment by javisantana** [comment]
this is a problem in carto parser

**Comment by iriberri** [comment]
Related: http://gis.stackexchange.com/questions/139881/is-it-possible-to-include-in-cartocss-string-values-in-cartodb

**Comment by rochoa** [comment]
As @javisantana  is pointing this is a problem with carto parser/symbolizer.

It works if you use:

```css
text-name: "'\"quotes are ok\"'";
```

But combining it with columns it escapes the glue text.

One option is to prepare the `text-name` with the query:

```sql
SELECT format('%s "%s"', name, description) as label, * FROM table_name
```

```css
#table_name::labels {
  text-name: [label]; // using label here
  text-face-name: 'DejaVu Sans Book';
  text-size: 14;
  text-label-position-tolerance: 10;
  text-fill: #000;
  text-halo-fill: #FFF;
  text-halo-radius: 1;
  text-dy: -10;
  text-allow-overlap: true;
  text-placement: point;
  text-placement-type: simple;
}
```

As there is an alternative solution for this I would de-prioritize this issue. What do you think?

p.s.: The stackexchange issue is not related, that's another issue. Feel free to create a different issue.
