### ISSUE TITLE
svg marker not rendering well (the shape is ok, but the color is missing)

### ISSUE THREAD

**Issue by oriolbx** [CartoDB/cartodb#5268]
The svg files added as markers they are showing in some cases correctly and in other cases in black.

**Steps:** 
* Add from the CSS option from the editor the CSS file:

```css
#populated_places_1{
 
  marker-placement: point;
  marker-type: ellipse;
  marker-width: 10;
  marker-file: url(https://dl.dropboxusercontent.com/u/51582502/name.svg);
  marker-allow-overlap: true;
} 
```
And the result that you get with level zoom = 6 is this:
![screen shot 2015-08-27 at 16 53 15](https://cloud.githubusercontent.com/assets/11177693/9523884/56b1e188-4cdc-11e5-9dff-875dc6780e6f.png)
 The result that you get with level zoom = 5 is this:
![screen shot 2015-08-27 at 17 03 43](https://cloud.githubusercontent.com/assets/11177693/9524149/a30be9ec-4cdd-11e5-84b0-70c13b68d966.png)

@iriberri and me, we were trying different buffer sizes and it was showing also different behaviours.
