### ISSUE TITLE
White to black color-scale has a color in the wrong order

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/cartodb#5342]
```css
/** choropleth visualization */

#abc{
  polygon-fill: #F7F7F7;
  polygon-opacity: 0.8;
  line-color: #FFF;
  line-width: 0.5;
  line-opacity: 1;
}
#abc [ hour <= 23] {
   polygon-fill: #252525;
}
#abc [ hour <= 22] {
   polygon-fill: #525252;
}
#abc [ hour <= 21] {
   polygon-fill: #737373;
}
#abc [ hour <= 20] {
   polygon-fill: #969696;
}
#abc [ hour <= 19] {
   polygon-fill: #BDBDBD;
}
#abc [ hour <= 18] {
   polygon-fill: #D9D9D9;
}
#abc [ hour <= 17] {
   polygon-fill: #F7F7F7;
}
```

to me it looks like #D9D9D9; and #BDBDBD; are reversed

to recreate, load any polygon dataset and make a choropleth withe the wizard. choose the white to black ramp
