### ISSUE TITLE
Cannot use a # character in a string as a CartoCSS selector

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#5419]
Copied from: http://gis.stackexchange.com/questions/139881/is-it-possible-to-include-in-cartocss-string-values-in-cartodb

I have a few tables in CartoDB that come from an external source. There is a name column that contains a few values with # in them. I would like to style particular features in the table, so I use CartoCSS like this:

``` css
#plans{
  polygon-fill: #FF6600;
  polygon-opacity: 0.7;
  line-color: #FFF;
  line-width: 1;
  line-opacity: 1;

  [name="Plan #1"] {
    polygon-fill: green;
  }
}
```

It works fine with most of the features, but when there is a # in the name column (as above) I always get an error:

```
line 14: Invalid code: [name="Plan #layer0 {
```

I've tried escaping the # in obvious ways (#, '#), but nothing works. Is there a way to do this? And is this a limitation of CartoDB or CartoCSS?

cc @rochoa
