### ISSUE TITLE
Tile edges appearing in Editor maps

### ISSUE THREAD

**Issue by ztephm** [CartoDB/cartodb#6125]
Hi @zenitraM I think you & @iriberri were helping with this?

Tile edges are showing even with CartoCSS buffer-size increased:
## Context

![screen shot 2015-11-12 at 12 01 47 pm](https://cloud.githubusercontent.com/assets/1779444/11124903/39a293e0-8935-11e5-9c88-de9f7762a708.png)
## Process
1. Add polygon layer to your map 
2. Re-add same polygon layer, then apply CartoCSS to get drop-shadow effect:
   
   ``` css
   #ne_50m_land{
   polygon-fill: #275384;
   image-filters: agg-stack-blur(50,50);
   polygon-geometry-transform: translate(2,2);
   polygon-opacity: 0.7;
   line-color: #FFF;
   line-width: 0.5;
   line-opacity: 1;
   comp-op: dst-over;
   }
   ```
3. Also increase buffer area (put in all layers):
   
   ``` css
   #ne_50m_land{
   Map {
   buffer-size:400;
   }
   }
   ```
## Expected result

Smooth gradients instead of offsets at tile edges.
## Current result

![screen shot 2015-11-12 at 12 08 13 pm](https://cloud.githubusercontent.com/assets/1779444/11126563/7c448a70-893d-11e5-97b8-172dabd2e207.png)

---
## Examples
- http://bit.ly/1GWCAEv
- http://bit.ly/1Y75upF

![screen shot 2015-11-12 at 1 07 22 pm](https://cloud.githubusercontent.com/assets/1779444/11126740/6351c126-893e-11e5-8ccc-e62152af2eda.png)

My examples use a ton of repeated polygon layers & comp-ops, but this is also happening for users with heatmaps: 
S/B 7288453

**Comment by ztephm** [comment]
* [ ] @ztephm follow up with S/B 7288453 when fixed

**Comment by zenitraM** [comment]
cc @rochoa

**Comment by rochoa** [comment]
This is not gonna be an easy one to solve. Also: it seems we're affected by this issue: https://github.com/mapbox/carto/issues/270

**Comment by xavijam** [comment]
There has been no activity on this issue for more several months. We are closing it. If you think this still needs to be addressed please open a new issue.

**Comment by ztephm** [comment]
Hi - is this issue fixable in our latest Mapnik version? Still getting tile edges showing with same STR above:

![screen shot 2017-06-09 at 4 40 06 pm](https://user-images.githubusercontent.com/1779444/26993715-690e7780-4d32-11e7-84ba-ac9c977b5acd.png)

[tile_edge_save (on 2017-06-09 at 20.40.35).zip](https://github.com/CartoDB/cartodb/files/1065196/tile_edge_save.on.2017-06-09.at.20.40.35.zip)

This is shadow CartoCSS:
```css
Map {
  buffer-size:400;
}
#ne_50m_land{
  polygon-fill: #275384;
  image-filters: agg-stack-blur(50,50);
  polygon-geometry-transform: translate(2,2);
  polygon-opacity: 0.7;
  line-color: #FFF;
  line-width: 0.5;
  line-opacity: 1;
  comp-op: dst-over;
}
```
