### ISSUE TITLE
Tiles with dynamically resized markers not rendering properly at zoom 18

### ISSUE THREAD

**Issue by jqnatividad** [CartoDB/cartodb#6383]
Based on the zoom level, the viz below dynamically changes marker-width to simulate a 150-ft radius.

http://data.beta.nyc/dataset/active-manhattan-payphone-locations/resource/8f53f743-ea10-4e55-8227-713431a12b0d/view/d42fd13c-c589-4108-bdd1-1224c109c144

``` css
/** simple visualization */

#manhattan_active_payphones_pre_linknyc{
  marker-fill-opacity: 0.9;
  marker-line-color: #FFF;
  marker-line-width: 0;
  marker-line-opacity: 1;
  marker-placement: point;
  marker-type: ellipse;
  marker-fill: #5CA2D1;
  marker-allow-overlap: true;
  marker-comp-op: multiply;
}

#manhattan_active_payphones_pre_linknyc [zoom>18]{
  marker-width: 680;
}

#manhattan_active_payphones_pre_linknyc [zoom=18]{
  marker-width: 340;
}

#manhattan_active_payphones_pre_linknyc [zoom=17]{
  marker-width: 170;
}
.
. /** other conditional CartoCSS statements **/
.
#manhattan_active_payphones_pre_linknyc [zoom=11]{
  marker-width: 2.125;
}
```

However, at zoom level 18, the map looks like this:
![betanyc_s_community_data_portal](https://cloud.githubusercontent.com/assets/1980690/12281240/52e3d8fc-b962-11e5-84d3-f9864ef916b0.jpg)

It still works, but its not rendered properly.
