### ISSUE TITLE
Failed export with bad config continues to poll status

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#7639]
1. set a invalid S3 entry in the `app_config.yml` file, e.g.:
```yml
    s3:
      access_key_id:
      secret_access_key:
      bucket_name:
      url_ttl:
      async_long_uploads: false
```
2. open a map and try to export it

**Expected result:**

- The polling to stop after the first request having state `failed`.
- Some more useful information about invalid config

**Actual result:**

- An error message (👍 ), but the export polling don't stop (👎 ) 
- errors found on `select entries from logs order by created_at desc limit 1;` on `carto_db_development` shows:
```
 2016-06-03 07:32:39 UTC: Exporting: #<NoMethodError: undefined method `[]' for nil:NilClass>                +
 /home/ubuntu/www/production.cartodb.com/current/app/models/carto/visualization_export.rb:45:in `run_export!'+
 /home/ubuntu/www/production.cartodb.com/current/lib/resque/exporter_jobs.rb:11:                             +
``` which if I understood it correctly is due to the invalid config entry for the S3 key. A guard there and some more useful output for devop would be useful?
