### ISSUE TITLE
Category values with apostrophes are generating an invalid cartocss

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#7681]
For example, a layer with this cartocss:

```css
#layer {
  marker-width: 10;
  marker-fill: ramp([psamanager], (#DDDDDD, #A6CEE3, #1F78B4, #B2DF8A, #33A02C, #FB9A99, #E31A1C, #FDBF6F, #FF7F00, #CAB2D6), ('Others', 'Cleveland, Maggie', 'Elder, Steve', 'Field, Adrian', 'Figone, Joe', 'Miller, John', 'O'Brien, Teresa', 'O'Connor, Tom', 'Sheehy, Chuck', 'Watkins, Robert'));
  marker-allow-overlap: true;
  marker-line-width: 2;
  marker-line-color: #FFFFFF;
  marker-line-opacity: 1;
}
```

And it is sent in the layer as:

`"#layer { marker-width: 10; marker-fill: ramp([psamanager], (#DDDDDD, #A6CEE3, #1F78B4, #B2DF8A, #33A02C, #FB9A99, #E31A1C, #FDBF6F, #FF7F00, #CAB2D6), ('Others', 'Cleveland, Maggie', 'Elder, Steve', 'Field, Adrian', 'Figone, Joe', 'Miller, John', 'O'Brien, Teresa', 'O'Connor, Tom', 'Sheehy, Chuck', 'Watkins, Robert')); marker-allow-overlap: true; marker-line-width: 2; marker-line-color: #FFFFFF; marker-line-opacity: 1; }"`

cc @javisantana
