### ISSUE TITLE
Turbo issue with analysis layers

### ISSUE THREAD

**Issue by AbelVM** [CartoDB/cartodb#8390]
This layer, linked with a sampling analysis to a source node with SQL:
```sql
SELECT * FROM solutions.lg_grow
```
Aggregated with hexabins, and using CSS:
```css
#layer {
  polygon-fill: ramp([agg_value], (#fde0c5, #facba6, #f8b58b, #f59e72, #f2855d, #ef6a4c, #eb4a40), quantiles);
  polygon-opacity: 0.8;
  line-width: 1;
  line-color: #3B3B58;
  line-opacity: 1;
  [zoom>=13]{
    polygon-opacity: 0;
  	line-opacity: 0;
  }
}
```
Is triggering an error 400 like:
`Request to Maps API failed: turbo-carto: Unable to process "polygon-fill". Reason: Unable to compute ramp. Reason: parse error - invalid geometry. Context: {"selector":"#layer","source":{"start":{"line":2,"column":3},"end":{"line":2,"column":110}}}`

In the request: https://solutions.cartodb.com/api/v1/map/named/tpl_a544bb1e_3ed4_11e6_b932_0ea31932ec1d?stat_tag=a544bb1e-3ed4-11e6-b932-0ea31932ec1d&filters=%7B%22dataviews%22%3A%7B%2216a9ac7f-a317-411c-a8a2-025af4998468%22%3A%7B%22min%22%3A99.65000000000009%2C%22max%22%3A992%7D%2C%22ecff4896-f987-4157-98e4-dcdc4f38cfa7%22%3A%7B%22min%22%3A0%2C%22max%22%3A107%7D%7D%7D

With payload: `{"layer0":1,"layer1":1,"layer2":1,"styles":{}}`

Loading the request in a new tab, gives:
`{"errors":["Only authenticated users can get template maps"],"errors_with_context":[{"type":"unknown","message":"Only authenticated users can get template maps","http_status":403}]}`

Due to privacy concerns, URL of the vis on request

cc @rochoa
