### ISSUE TITLE
Add button to invert color ramps

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#8479]
When having a ramp selected, it would be great to be able to flip it with a button.

**Comment by saleiva** [comment]
as @AbelVM, shouldn't be this available in turbo-carto @rochoa ?

**Comment by AbelVM** [comment]
Thre's an already open issue there: https://github.com/CartoDB/turbo-carto/issues/35

**Comment by rochoa** [comment]
It should, but we didn't have time to implement it yet.

**Comment by rochoa** [comment]
BTW have in mind that sometimes the builder is sending the colours tuple itself, not relying on cartocolor ramps. The `reverse` function would work in those cases also, but the builder could reverse the tuple before sending it as it will have the same effect.

Example:

```css
#layer {
  polygon-fill: ramp([avg_price], reverse(red, green, blue));
}
```

would be the same as


```css
#layer {
  polygon-fill: ramp([avg_price], (green, blue, red));
}
```

And that's not as useful as:


```css
#layer {
  polygon-fill: ramp([avg_price], reverse(colorbrewer(Reds)));
}
```
