### ISSUE TITLE
Numeric ramp does not "find" the target column

### ISSUE THREAD

**Issue by AbelVM** [CartoDB/cartodb#9401]
Working within builder but not in the embed

Example: https://team.carto.com/u/abel/builder/aa9b66ae-0d41-11e6-bcde-0e31c9be1b51/embed

CartoCSS:
```css
#layer {
  marker-comp-op: lighten;
  marker-width: ramp([total], 5, 10, quantiles);
  marker-fill: ramp([total], (#f3e79b, #fac484, #f8a07e, #eb7f86, #ce6693, #a059a0, #5c53a5), quantiles);
  marker-allow-overlap: true;
  marker-line-width: 0;
  marker-line-color: #fff;
  marker-line-opacity: 1;
}
```
Message: 
`"Failed to process "marker-width" property: unable to compute ramp, column "total" does not exist"`

The column is there: `abel.imd_2013`
